name: Run Translator Manually
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      folder:
        description: 'URI to folder containing translations'
        required: true
        default: 'example-data'
      from:
        description: 'Source language code (2-letter ISO, e.g. en)'
        required: true
        default: 'en'
      to:
        description: 'Target language code (2-letter ISO, e.g. fr)'
        required: true
        default: 'fr'

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read source JSON into variable
        id: read_source
        run: |
          echo "source_json=$(base64 -w 0 example-data/en.json)" >> $GITHUB_OUTPUT

      - name: Run Translator
        id: run_translator
        uses: HamieScripts/translator@main
        with:
          source-json: ${{ steps.read_source.outputs.source_json }}
          from: en
          to: fr

      - name: Write translated JSON to file
        run: |
          echo '${{ steps.run_translator.outputs.translated }}' > example-data/fr.json

      - name: Commit and push translated file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add example-data/${{ github.event.inputs.to }}.json
          git commit -m "Add translated ${{ github.event.inputs.to }}.json from GitHub Action" || echo "No changes to commit"
          git push
