name: Run Translator Manually

on:
  workflow_dispatch:
    inputs:
      folder:
        description: 'URI to folder containing translations'
        required: true
        default: './example-data'
      from:
        description: 'Source language code (2-letter ISO, e.g. en)'
        required: true
        default: 'en'
      to:
        description: 'Target language code (2-letter ISO, e.g. fr)'
        required: true
        default: 'fr'

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Run Translator
        uses: HamieScripts/translator@main
        with:
          folder: ${{ github.event.inputs.folder }}
          from: ${{ github.event.inputs.from }}
          to: ${{ github.event.inputs.to }}